"""Add global regulation library

Revision ID: 4716e2c70d81
Revises: e5f6a7b8c9d0
Create Date: 2026-07-29 18:41:42.622519

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4716e2c70d81'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regulations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('act_name', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=100), nullable=True),
    sa.Column('jurisdiction', sa.String(length=255), nullable=True),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('processing_status', postgresql.ENUM('UPLOADED', 'PROCESSING', 'PROCESSED', 'FAILED', name='processingstatus', create_type=False), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(length=150), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=2000), nullable=True),
    sa.Column('mongo_document_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulations_document_hash'), 'regulations', ['document_hash'], unique=True)
    op.create_index(op.f('ix_regulations_mongo_document_id'), 'regulations', ['mongo_document_id'], unique=False)
    op.create_index(op.f('ix_regulations_uploaded_by'), 'regulations', ['uploaded_by'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('regulation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['regulation_id'], ['regulations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("DELETE FROM compliance_reports")
    op.add_column('compliance_reports', sa.Column('regulation_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('ix_compliance_reports_regulation_document_id'), table_name='compliance_reports')
    op.create_index(op.f('ix_compliance_reports_regulation_id'), 'compliance_reports', ['regulation_id'], unique=False)
    op.drop_constraint(op.f('compliance_reports_regulation_document_id_fkey'), 'compliance_reports', type_='foreignkey')
    op.create_foreign_key(None, 'compliance_reports', 'regulations', ['regulation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('compliance_reports', 'regulation_document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_reports', sa.Column('regulation_document_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'compliance_reports', type_='foreignkey')
    op.create_foreign_key(op.f('compliance_reports_regulation_document_id_fkey'), 'compliance_reports', 'documents', ['regulation_document_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_compliance_reports_regulation_id'), table_name='compliance_reports')
    op.create_index(op.f('ix_compliance_reports_regulation_document_id'), 'compliance_reports', ['regulation_document_id'], unique=False)
    op.drop_column('compliance_reports', 'regulation_id')
    op.drop_table('reports')
    op.drop_index(op.f('ix_regulations_uploaded_by'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_mongo_document_id'), table_name='regulations')
    op.drop_index(op.f('ix_regulations_document_hash'), table_name='regulations')
    op.drop_table('regulations')
    # ### end Alembic commands ###