"""Add report caching hashes

Revision ID: f1328c50a911
Revises: da12c5f47f17
Create Date: 2026-07-29 19:30:37.068381

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f1328c50a911'
down_revision: Union[str, Sequence[str], None] = 'da12c5f47f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_reports', sa.Column('policy_hash', sa.String(length=255), nullable=True))
    op.add_column('compliance_reports', sa.Column('regulation_hash', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_compliance_reports_policy_hash'), 'compliance_reports', ['policy_hash'], unique=False)
    op.create_index(op.f('ix_compliance_reports_regulation_hash'), 'compliance_reports', ['regulation_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compliance_reports_regulation_hash'), table_name='compliance_reports')
    op.drop_index(op.f('ix_compliance_reports_policy_hash'), table_name='compliance_reports')
    op.drop_column('compliance_reports', 'regulation_hash')
    op.drop_column('compliance_reports', 'policy_hash')
    # ### end Alembic commands ###